diary/urls.py
from django.urls import path
from django.urls.conf import include
from . import views

app_name = 'diary'

urlpatterns = [
    path('', views.index, name='index'),
    path('analysis/', views.analysis, name='analysis'),
    path('result/', views.result, name='result'),
    ]

return/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

diary/models.py
from django.db import models

# Create your models here.

class User(models.Model):
    id = models.IntegerField()
    name = models.CharField(max_length = 5)
    count = models.IntegerField(default = 0)
    email = models.EmailField(primary_key = True)

class Result(models.Model):
    id = models.IntegerField(primary_key = True)
    happiness = models.FloatField()
    sadness = models.FloatField()
    anger = models.FloatField()
    fear = models.FloatField()
    email = models.ForeignKey(User, on_delete=models.PROTECT)
    
class Content(models.Model):
    id = models.IntegerField(primary_key = True)
    email = models.ForeignKey(User, on_delete=models.PROTECT)
    text = models.TextField(max_length=1000)

diary/forms.py
from django.forms import ModelForm
from diary.models import Content, User, Result

class ContentForm(ModelForm):
    class Meta:
        model = Content
        fields = ['text']

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['id', 'name', 'count', 'email']
        
class ResultForm(ModelForm):
    class Meta:
        model = Result
        fields = ['id', 'happiness', 'sadness', 'anger', 'fear', 'email']

diary/views.py
import os
import re
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import User, Result, Content
from .forms import ContentForm, UserForm, ResultForm
import os
import re

import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import gluonnlp as nlp
import numpy as np
from tqdm import tqdm, tqdm_notebook
from tqdm.notebook import tqdm

from kobert.utils import get_tokenizer 
from kobert.pytorch_kobert import get_pytorch_kobert_model 

from transformers import AdamW
from transformers import WarmupLinearSchedule as get_linear_schedule_with_warmup
from sklearn.model_selection import train_test_split
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

module_dir = os.path.dirname(__file__)
max_len = 64
batch_size = 64
warmup_ratio = 0.1
num_epochs = 1
max_grad_norm = 1 
log_interval = 200 
learning_rate =  5e-5

class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, max_len,
                 pad, pair):
        transform = nlp.data.BERTSentenceTransform(
            bert_tokenizer, max_seq_length=max_len, pad=pad, pair=pair)

        self.sentences = [transform([i[sent_idx]]) for i in dataset]
        self.labels = [np.int32(i[label_idx]) for i in dataset]

    def __getitem__(self, i):
        return (self.sentences[i] + (self.labels[i], ))

    def __len__(self):
        return (len(self.labels))

class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 num_classes=4,
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate
                 
        self.classifier = nn.Linear(hidden_size , num_classes)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)
    
    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)
        
        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device))
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

def index(request):
    return render(request, 'diary/diary.html')


def analysis(request):
    if request.method == 'POST':
        data = request.read().decode('utf-8')
        text = data_preprocess(data)
        print(data)
        file ='C:/Users/kie69/Desktop/project2/return/diary/kobert_ending_finale.pt'
        device = torch.device("cuda:0")
        bertmodel, vocab = get_pytorch_kobert_model()
        model = BERTClassifier(bertmodel,  dr_rate=0.5).to(device)
        model.load_state_dict(torch.load(file))
        model.eval()

        result = predict(model, text)
        results = calc_result(result)

        print(results)
        return JsonResponse({"results":results})




def result(request):
    if request.method == 'POST':
        form = ContentForm(request.POST)
        data = form.data['text']
        
        return render(request, 'diary/result.html', {'text':data})

def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc

    
def load_model(file):
    device = torch.device("cuda:0")
    bertmodel, vocab = get_pytorch_kobert_model()
    model = BERTClassifier(bertmodel,  dr_rate=0.5).to(device)
    model.load_state_dict(torch.load(file))
    model.eval()
    
    return model
    
def data_preprocess(data):
    raw = re.split('[\r\n\.\?\!]', data)
    text = []
    
    for val in raw:
        if val == '':
            continue
        text.append([val, 0.0])
    
    
    print(text)
    return text

def predict(model, text):
    device = torch.device("cuda:0")
    max_len = 64
    batch_size = 64
    warmup_ratio = 0.1
    num_epochs = 2
    max_grad_norm = 1
    log_interval = 200 
    learning_rate =  5e-5
    
    tokenizer = get_tokenizer()
    bertmodel, vocab = get_pytorch_kobert_model()
    tok = nlp.data.BERTSPTokenizer(tokenizer, vocab, lower=False)
    data_test = BERTDataset(text, 0, 1, tok, max_len, True, False)
    test_dataloader = torch.utils.data.DataLoader(data_test, batch_size=batch_size, num_workers=0)
    model.eval()
    
    answer=[]
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm_notebook(test_dataloader)):
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        max_vals, max_indices = torch.max(out, 1)
        answer.append(max_indices.cpu().clone().numpy())
    
    result = F.softmax(out)
    
    print(result)
    return result
    
def calc_result(result):
    happy = 0.0
    joy = 0.0
    sadness = 0.0
    angry = 0.0
    result = result.detach().cpu().clone().numpy()
    
    for data in result:
        happy += data[0]
        joy += data[1]
        sadness += data[2]
        angry += data[3]
       
    print(result) 
    result = [happy, joy, sadness, angry]
    
    
    
    results = normalize(result)
    results = [0.1 if x == 0.0 else x for x in results]
    results = {'happy': results[0], 'joy': results[1], 'sadness': results[2], 'angry': results[3]}

    return results


def normalize(result):
    max_ = max(result)
    min_ = min(result)
    list = []
    for val in result:
        val = (val - min_)/(max_ - min_)
        list.append(round(val,2))

    print(list)
    return list

templates/diary/diary.html
{% extends 'diary/index.html' %}
{% load static %}
{% block title %}<title>return :Diary</title>{% endblock %}

{% block main %}
<form action = "{% url 'diary:result' %}" method='POST' id = text>
{% csrf_token %}
<div id = 'body'>
<h1 class="cover-heading">오늘의 일기 작성하기</h1>
    <p class="lead" id="loading">
    <textarea name = 'text' form = 'text' cols ="60" rows ="10" placeholder="" autofocus required ></textarea>
    </p>
    <p class="lead">
      <button type = "submit" class = "btn btn-lg btn-secondary" value = "submit" id = "result">분석 하기</button>
    </p>
</div>
</form>
{% endblock %}

templates/diary/index.html
<!-- {% load static %} -->
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>return :Diary</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSS
    ================================================== -->
    {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">    

    <!-- script
    ================================================== -->
    <script src="js/modernizr.js"></script>
    <script defer src="js/fontawesome/all.min.js"></script>

    <!-- favicons
    ================================================== -->
    <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
    <link rel="manifest" href="site.webmanifest">

</head>

<body id="top">

    <!-- preloader
    ================================================== -->
    <div id="preloader">
        <div id="loader" class="dots-fade">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <!-- Header
    ================================================== -->
    <header class="s-header">

        <div class="row">

            <div class="s-header__content column" style="min-height: 0rem;">
                <h1 class="s-header__logotext">
                    <a href="index.html" title="">return :Diary</a>
                </h1>
                <p class="s-header__tagline"> 감정 분석 다이어리</p>
            </div>

        </div> <!-- end row -->

       <nav class="s-header__nav-wrap">

           <div class="row">

                <ul class="s-header__nav">
                    <li class="current"><a href="index.html">Home</a></li>
                    <li><a href="demo.html">Demo</a></li>	
                    <li><a href="archives.html">contact</a></li>
                    <li><a href="https://lajancia.github.io/">Blog</a></li>
                </ul> <!-- end #nav -->

           </div> 

        </nav> <!-- end #nav-wrap -->

        <a class="header-menu-toggle" href="#0" title="Menu"><span>Menu</span></a>

    </header> <!-- Header End -->

    <!-- Content
    ================================================== -->
    <div class="s-content" style=" padding-left:300px">

        <!-- <div class="row"> -->

            <div id="main" class="s-content__main large-8 column">

                <article class="entry">

                    <header class="entry__header">

                        <h2 class="entry__title h1">
                            <a href="single.html" title="">Diary</a>
                        </h2>

                        <div class="entry__meta">
                            <ul>
                                <li>Aug 20, 2021</li>
                                <li><a href="#" title="" rel="category tag">diary</a></li>
                                <li>Hwang</li>
                            </ul>
                        </div>
                     
                    </header>
                    
                    <div class="entry__content">
                      {% block main %}
                      {% endblock %}
                    </div> 

                </article> <!-- end entry -->

                
           <!-- </div> end main -->

           

       </div> <!-- end row -->

   </div> <!-- end content-wrap -->

    <!-- Footer
    ================================================== -->
    <footer class="s-footer">

        <div class="row s-footer__top">
            <div class="column">
               
            </div>
        </div> <!-- end footer__top -->

        <div class="row s-footer__bottom">

            <div class="large-6 tab-full column s-footer__info">
                <h3 class="h6">Return;</h3>

                
            </div>

           

            <div class="large-6 tab-full column">
                <div class="row">

                  <div class="large-8 tab-full column">

                    <h3 class="h6">데이터청년캠퍼스</h3>
                    
                    
      
                </div>
        
                    <div class="large-4 tab-full column">
                        <h3  class="h6">Navigate</h3>
        
                        <ul class="s-footer__list s-footer-list--nav group">
                            <li><a href="#0">Home</a></li>
                            <li><a href="#0">Blog</a></li>
                            <li><a href="#0">About</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="ss-copyright">
                <span>© Copyright Keep It Simple 2019</span> 
                <span>Design by <a href="https://www.styleshout.com/">StyleShout</a></span>
            </div>

        </div> <!-- end footer__bottom -->

        <div class="ss-go-top">
            <a class="smoothscroll" title="Back to Top" href="#top">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0l8 9h-6v15h-4v-15h-6z"/></svg>
            </a>
        </div> <!-- end ss-go-top -->

    </footer> <!-- end Footer-->

    <!-- Java Script
    ================================================== -->
    <script src="js/jquery-3.2.1.min.js"></script>
    <script src="js/main.js"></script>

</body>

</html>

templates/diary/result.html
{% extends 'diary/index.html' %}
{% load static %}

{% block title %}<title>return :Diary 감성분석 다이어리</title>{% endblock %}

{% block main %}
{% csrf_token %}
<style>
#piechart{
    
    text-align:left;
    
}
#columnchart_values{
    text-align:right;
    
}
#sentence{
  clear:right;
  font-family: 'Jua', sans-serif;
  text-align:center;
  color:#96b753;
  font-size: 70px;
}
#box{
  padding:250px;
}
</style>
<input type = 'hidden' id = 'text' value = '{{ text }}'>
<div id = 'loading'>
<h1 class="cover-heading">조금만 기다려 주세요...</h1>
</div>
<div id = 'result' style='display:none'>
<h1 class="cover-heading">오늘의 감정 분석 결과</h1>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Jua&display=swap" rel="stylesheet">
<div id="sentence" style="padding:100px;"></div>
<div style="float:left">
<div id="piechart" style="width: 500px; height: 500px; float:left;"></div>
<div id="columnchart_values" style="width: 100px; height: 100px; float:right;"></div>
</div>
<div id="box"></div>
</div>


<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type = "text/javascript">



const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
console.log(csrftoken);
var text = document.getElementById('text').value;
var result = {};
console.log(text);
var loading = document.getElementById('loading');
var page = document.getElementById('result');
var pie_result={};
var max=0;
var find=[];


function find_max(result){
    find.push(result.results.happy);
    find.push(result.results.joy);
    find.push(result.results.sadness);
    find.push(result.results.angry);

    var num=Math.max.apply(null,find);
    for(var i=0;i<4;i++){
      if(find[i]==num){
        max=i;
      }
    }
    
};

function good_word(max){
  var sentence=['내일도 행복한 하루를 간직해요:D', '내일도 즐거움이 가득한 오늘 하루!', '괜찮아요. 오늘은 조금 쉬어볼까요?','내일은 분명 오늘보다 훨씬 좋을 거예요!'];
  return sentence[max]

};
function wait(result){
    pie_result=result
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    google.charts.load("current", {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawcolumn);
    

    
}

function drawcolumn() {
      var data = google.visualization.arrayToDataTable([
        ["Element", "Density", { role: "style" } ],
        ["sad", pie_result.results.sadness, "color:#bfc7a7"],
        ["joy", pie_result.results.joy, "color:#96b753"],
        ["angry", pie_result.results.angry, "color:#c6e686"],
        ["happy", pie_result.results.happy, "color: #446418"]
      ]);

      var view = new google.visualization.DataView(data);
      view.setColumns([0, 1,
                       { calc: "stringify",
                         sourceColumn: 1,
                         type: "string",
                         role: "annotation" },
                       2]);

      var options = {
        title: "막대그래프 분석 결과",
        width: 600,
        height: 400,
        bar: {groupWidth: "95%"},
        legend: { position: "none" },
      };
      var chart = new google.visualization.ColumnChart(document.getElementById("columnchart_values"));
      chart.draw(view, options);
  }

function drawChart() {

var data = google.visualization.arrayToDataTable([
  ['Task', 'Hours per Day'],
  ['SAD',     pie_result.results.sadness],
  ['JOY',      pie_result.results.joy],
  ['ANGRY',  pie_result.results.angry],
  ['HAPPY', pie_result.results.happy],

]);

var options = {
  title: '파이그래프 분석 결과',
  colors:['#bfc7a7','#96b753' ,'#c6e686','#446418']

};

var chart = new google.visualization.PieChart(document.getElementById('piechart'));

chart.draw(data, options);
}

function setInnerHTML(){
          const element=document.getElementById('sentence');
          element.innerHTML+='<div>'+good_word(max)+'</div>';
        }


fetch('{% url "diary:analysis" %}', {
	method: 'POST',
	credentials: 'same-origin',
	headers: {
		'X-Requested-With':'XMLHttpRequest',
		'X-CSRFToken': csrftoken,
	},
	body: text
	})
	.then(response => response.json())
	.then(json => {
		result = json
    pie_result=result
    wait(result)
    find_max(result)
    setInnerHTML()
		loading.style.display ='none'
		page.style.display = 'block'
	})

    </script>
{% endblock %}